const ADD_INGREDIENT = "ADD_INGREDIENT";
const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
const SET_INGREDIENTS = "SET_INGREDIENTS";
const FETCH_INGREDIENTS_FAILD = "FETCH_INFREDIENTS_FAILD";

export {
  ADD_INGREDIENT,
  REMOVE_INGREDIENT,
  SET_INGREDIENTS,
  FETCH_INGREDIENTS_FAILD
};