const PURCHASE_BURGER_START = "PURCHASE_BURGER_START";
const PURCHASE_BURGER_SUCCESS = "PURCHASE_BURGER_SUCCESS";
const PURCHASE_BURGER_FAIL = "PURCHASE_BURGER_FAIL";
const PURCHASE_INIT = "PURCHASE_INIT";

const FETCH_ORDERS_START = "FETCH_ORDERS_START";
const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
const FETCH_ORDERS_FAIL = "FETCH_ORDERS_FAIL";

export default {
  PURCHASE_BURGER_SUCCESS,
  PURCHASE_BURGER_FAIL,
  PURCHASE_BURGER_START,
  PURCHASE_INIT,
  FETCH_ORDERS_START,
  FETCH_ORDERS_SUCCESS,
  FETCH_ORDERS_FAIL
};