const SINGUP_START = "SINGUP_START";
const SINGUP_SUCCESS = "SINGUP_SUCCESS";
const SINGUP_FAIL = "SINGUP_FAIL";

const SINGIN_START = "SINGIN_START";
const SINGIN_SUCCESS = "SINGIN_SUCCESS";
const SINGIN_FAIL = "SINGIN_FAIL";

const SINGOUT = "SINGOUT";

const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";

export {
  SINGUP_START,
  SINGUP_SUCCESS,
  SINGUP_FAIL,
  SINGIN_START,
  SINGIN_SUCCESS,
  SINGIN_FAIL,
  SINGOUT,
  AUTH_REDIRECT_PATH
};